const NS_REQUIREMENT = 'REQUIREMENT';

export default {
    REQUIREMENT_LIST: NS_REQUIREMENT + '/LIST',
    REQUIREMENT_DETAIL: NS_REQUIREMENT + '/DETAIL',
    REQUIREMENT_NAME: NS_REQUIREMENT + '/NAME',
    REQUIREMENT_PAGINATION: NS_REQUIREMENT + '/PAGINATION'
};